### ISSUE TITLE
Canvas Fingerprinting

### ISSUE THREAD

**Issue by jorg35** [jake-cryptic/AbsoluteDoubleTrace#1]
version.2.0.1 >>Your Fingerprint
Signature ✔ AD231A51
Uniqueness 99.89% (412 of 358283 user agents have the same signature)
---------------------
version.1.9.10 >>Your Fingerprint
Signature ✔ 014E5EA4
Uniqueness 100% (0 of 358283 user agents have the same signature)
test page >>https://browserleaks.com/canvas
Something is wrong,it is worse !!

**Comment by jorg35** [comment]
It was supposed to be so good and it turned out worse. I was thinking to buy, but it is not worth it.

**Comment by jake-cryptic** [comment]
You can set the RGBA values manually in settings if you want, you don't have to.
By default Trace will choose these automatically for you. You know the protection is working when the value of the canvas fingerprint changes on each page reload as was shown in the link above :)

**Comment by jake-cryptic** [comment]
You don't have to set anything - the protection is working if every time you reload the page you get a new "Signature" on BrowserLeaks.

**Comment by jorg35** [comment]
As for me premium too expensive, no one will buy it in the countries of Eastern Europe.  Sorry for my English.
