### ISSUE TITLE
Google Header Removal - still show up in Firefox?

### ISSUE THREAD

**Issue by ReporterX** [jake-cryptic/AbsoluteDoubleTrace#10]
I believe it is a feature which is only useful if you use Chrome browser. I can see this option even I'm using Firefox. Perhaps it should be hidden in Firefox version. Thank you.

**Comment by jake-cryptic** [comment]
Whilst Chrome does send network requests using these headers so do many Google websites, so if you are a Firefox user using Google services then this is still useful.
