### ISSUE TITLE
Screen resolution spoofing can be detected. Need improvement 

### ISSUE THREAD

**Issue by ReporterX** [jake-cryptic/AbsoluteDoubleTrace#12]
It is easy to detect whether you are spoofing screen size. Let's say you use 1920×1080 which is one of the most common screen sizes.

Check `availWidth` and `availHeight` (which is 1040 or 1050 by default, should be lower than the screen height). Yours stays the same when spoofing which is abnormal.

Also Window `outerWidth` and `outerHeight`.

It would be great it can spoof `window.innerWidth` and `window.innerHeight` too. They are closely related to the screen size. To avoid fingerprinting, you will normally set it as if you maximize the window.

`window.innerWidth` is the easiest. It is just the same as the screen's.

As to `window.innerHeight`, take Windows 7 as an example, 
Windows 7's default taskbar - 40px for large icons, 30px for small icons
Firefox default toolbar interface (normal UI density) - 74px
Total - 114px
So `window.innerHeight` should be 966.

**Comment by jake-cryptic** [comment]
I'm aware of the issue and I'm planning improvements, they are on my private issue tracker :)

I will update this issue when the feature is in Trace.

**Comment by Atavic** [comment]
[The Design and Implementation of the Tor Browser](https://2019.www.torproject.org/projects/torbrowser/design/#fingerprinting-defenses) is an interesting read - scroll down to *Monitor, Widget, and OS Desktop Resolution*.

Tor gives a generic value of the browser's inner window, then the user should change the default OS taskbar by using some less common window manager, as javascript allows to uniquely recognize the OS used by calculating default taskbar height.

**Comment by jake-cryptic** [comment]
@Atavic Thanks for the link, just had a quick look over and it seems as though it will be useful for feature ideas

**Comment by jake-cryptic** [comment]
Feature is currently being implemented and will be in coming to Trace in version 2.3.1
