### ISSUE TITLE
Bug on test

### ISSUE THREAD

**Issue by bmbraga** [jake-cryptic/AbsoluteDoubleTrace#13]
I tested it with all the active settings, at https://browserleaks.com/ using the chrome plugin and none of the options is working, active or disabled the result is the same.

**Comment by jake-cryptic** [comment]
Hi,

Could you email me a backup file at absolutedouble@gmail.com so I can look into this.

To create a backup file, go to the Trace Options page, then under settings, click the "Trace Options" tab and you should see one called "Backup/Restore", download the file there and attach it to an email.

Thanks

**Comment by bmbraga** [comment]
I'm not having backup problems, the problem is that no option is working that is active.

**Comment by jake-cryptic** [comment]
The backup file is so that I can see how the settings are configured to better understand why the settings aren't working.

**Comment by bmbraga** [comment]
Oh yeah, sorry, it's attached.

Att,
Breno Braga

- BMBraga Internet // ClickGrátis


Em qua, 15 de mai de 2019 às 16:48, Jake Mcneill <notifications@github.com>
escreveu:

**Comment by bmbraga** [comment]
Your plugin is getting very good.

Can you download the https://ghostbrowser.com install, enable these
settings below and test at https://browserleaks.com/canvas?
To see the differences in the results, I would need to adjust your plugin
for this, so I would respond very well, how can you help me?
It would also be good, besides the random user agent, to be able to set a
user agent that I want.
I can also collaborate in what you need.

[image: image.png]

Att,
Breno Braga

- BMBraga Internet // ClickGrátis


Em qua, 15 de mai de 2019 às 17:28, Breno Braga <breno@bmbraga.com>
escreveu:

**Comment by bmbraga** [comment]
https://www.dropbox.com/sh/zrupod0ljuf05pg/AAB-Ndu3czj7oXTO7RglbZk6a?dl=0

**Comment by bmbraga** [comment]
Can you help me with this?

**Comment by jake-cryptic** [comment]
Hi,

Sorry it took so long for me to reply, I've had exams in the past month so have been very busy..

Unfortunately that browser isn't supported, and from taking a look at the features it offers they seem to interfere with Trace. I don't think there is much I can do about that right now but will continue looking into it and update this issue in the future.

**Comment by bmbraga** [comment]
I see, and I'm grateful. For your plugin to stay perfect, would you have implemented an otion to generate a fixed Fingerprinting Canvas by profile in chrome? And keep it safe, without being random.

**Comment by jake-cryptic** [comment]
A feature is planned where all of the data sent to web api's will remain the same for a browsing session rather than being regenerated at each page load, however this is not coming to Trace just yet as there are more protections I am adding first.

You can set your canvas profile to stay the same in Canvas fingerprinting settings :)

Thanks
