### ISSUE TITLE
JS Plugin Hide

### ISSUE THREAD

**Issue by gameb0y** [jake-cryptic/AbsoluteDoubleTrace#14]
Hello

If enabled "JS Plugin Hide",  I cant watch youtube videos in full screen.

Windows 7 x64
Tested:  Chrome Version 74, 75, 76, 77

**Comment by jake-cryptic** [comment]
I've made some changes which may fix the issue, they will take effect in version 2.3.2 which will be released tomorrow.

Thanks

**Comment by jake-cryptic** [comment]
Presumed to be fixed in 2.3.2, please re-open if you are still having this issue.
