### ISSUE TITLE
Improve WebRTC Protection

### ISSUE THREAD

**Issue by gameb0y** [jake-cryptic/AbsoluteDoubleTrace#16]
Hello

Can you add block "WebRTC Media Devices / Device Enumeration / Media Devices /  deviceId

https://browserleaks.com/webrtc

kind: audiooutput
deviceId: default
   label: n/a

    kind: audiooutput
deviceId: communications
   label: n/a

    kind: audiooutput
deviceId: 528710f2c68eft5dzz3425c2962bfc5b38fd9e202cf1bda99b3137d5a34d44ce
   label: n/a

**Comment by jake-cryptic** [comment]
Okay, so after looking into this further and seeing how effective it can be at tracking users, I've decided to implement it as soon as possible, will update this thread with more information soon.

**Comment by jake-cryptic** [comment]
This protection will be available in Trace 2.4 which is being released in a few days

**Comment by jake-cryptic** [comment]
Protection is now available in Trace 2.4
