### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by jorg35** [jake-cryptic/AbsoluteDoubleTrace#18]
Captcha does not work. in v.2.2.6 it's good. Win10, Waterfox 56.2.12  https://images91.fotosik.pl/218/ebc4252cc003f47dgen.png

**Comment by ookangzheng** [comment]
Me too on Mac Mojave Firefox and Chrome and Brave browser

https://imgur.com/a/x20Mobv

**Comment by jake-cryptic** [comment]
@jorg35 @ookangzheng

I'm having a hard time recreating the issue, could you email me a backup file at absolutedouble@gmail.com so I can look into this.

To create a backup file, go to the Trace Options page, then under settings, click the "Trace Options" tab and you should see one called "Backup/Restore", download the file there and attach it to an email.

Thanks

**Comment by jake-cryptic** [comment]
Thank you for the help, I've recieved your emails and have been able to recreate the issue on my own computer...

The issue may take a while to resolve because it is proving difficult to debug, there are no errors in the console... However this is my top priority right now.

Thanks again

**Comment by jake-cryptic** [comment]
I've pushed an update with a temporary work around in 2.3.2, a proper fix will be added in 2.3.3

**Comment by jake-cryptic** [comment]
A temporary work around for this issue is to open the Trace report panel and click "Pause Trace" then reload the page you're on

**Comment by jorg35** [comment]
A temporary but not resolved, in v.2.2.6 is good.

**Comment by jake-cryptic** [comment]
Fixed in Trace 2.3.4
