### ISSUE TITLE
navigator.userAgent & navigator.appVersion reveal true user agent in Chrome 

### ISSUE THREAD

**Issue by feythr** [jake-cryptic/AbsoluteDoubleTrace#2]
When the user agent randomiser is enabled, although the user agent in the request header is correctly spoofed, the `navigator.userAgent` and `navigator.appVersion` JavaScript properties reveal the true user agent (as can be seen on https://browserleaks.com/javascript).

This issue appears to be limited to Chrome, and isn't reproducable on Firefox. I've tested using Chrome 70 on both Mac and Windows.

**Comment by jake-cryptic** [comment]
Hi, I just pushed 2.0.4, can you make sure that User-Agent Randomiser is under "Run on all pages" in settings as shown in the screenshot attached
![Screenshot](https://user-images.githubusercontent.com/8399207/48221366-c3373500-e389-11e8-827e-002952e59a9d.png)

This setting should hopefully now work, if not please reopen this this issue.

**Comment by feythr** [comment]
@jake-cryptic Thanks for the quick fix (and for such a great extension to begin with)! I can confirm the issue is resolved :)

I did however just notice that the user agents for the macOS platform are slightly incorrect – I've opened https://github.com/jake-cryptic/AbsoluteDoubleTrace/issues/3.

**Comment by jake-cryptic** [comment]
No problem, glad I was able to resolve it! I shall look into fixing #3 now.
