### ISSUE TITLE
ReCaptcha (V2 & V3) Non-Functional

### ISSUE THREAD

**Issue by JK98062** [jake-cryptic/AbsoluteDoubleTrace#23]
ReCaptcha's are no longer functional while Trace is Enabled (even after "Pausing Trace on Page").

Can't be 100% certain of the culprit code as it doesn't actually throw any error codes in Console.

Further information which might assist with debugging: ReCaptcha's appear to be completely functional under Trace v2.2.5.
These are my findings so far after conducting 500 algorithmically randomised Site Tests:
w/ v2.2.5 | 99%>+ Success Rate with ReCaptcha. Only 1 Failure.
w/ v2.2.6 | ~93% Success Rate with ReCaptcha. 34 Failures.
w/ v2.3 & v2.3.1 | ~<70% Success Rate with ReCaptcha. 157 Failures. (Both Versions Identical)
w/ v2.3.2 & v2.3.3 | ~<30% Success Rate with ReCaptcha. ~342 Failures (Difference between Each Version was Negligible)
For further clarification, Failure = ReCaptcha Timing Out.

Hope that's of some assistance with narrowing down the culprit code.

Let me know if you need a hand with it.

**Comment by jake-cryptic** [comment]
Thanks for the information, I have identified the commit in my private repository which caused the issue however am still debugging the code itself. It is to do with the new injection method being used in Trace 2.3 hence it affects most protections.

Thanks

**Comment by jorg35** [comment]
Now I see what I paid for.Almost nothing works here.

**Comment by jake-cryptic** [comment]
Fixed in Trace 2.3.4

**Comment by jorg35** [comment]
So you fixed that nothing is showing the extension is useless.

**Comment by jake-cryptic** [comment]
@jorg35 If you're having problems with Trace open a new issue with more details.

**Comment by jorg35** [comment]
The v2.3.5 is fine.

**Comment by JK98062** [comment]
@jake-cryptic I think he either doesn't quite understand how GitHub works, or he's just a bit farkin' rude.

Either way, I'm glad you could debug the culprit code easily enough.
Also, thank you kindly, as it was starting to become more and more of an annoyance for me to have the ReCaptcha's fuck up. Seems some people really struggle to use manners these days, especially on here, so I just wanted to say thank you personally.

**Comment by jake-cryptic** [comment]
@JK98062 Sorry it took me so long to reply to this it got lost in my emails.

Thanks for your kind words and for raising the issue here with such detailed information, it really helped solve the issue.
