### ISSUE TITLE
Blacklist needed

### ISSUE THREAD

**Issue by opusforlife2** [jake-cryptic/AbsoluteDoubleTrace#25]
Can we have the option to run certain protections on all pages _except_ specified ones? The opposite of the Whitelist, basically.

**Comment by jake-cryptic** [comment]
You can do this in Trace, you just need to set a protection to be "Enabled on all pages" in settings and then whitelist the site you wish to not run it on and uncheck that protection.

An example:

Let's say I wanted to stop "JS Plugin Hide" from working on google.co.uk, I would create the following whitelist entry:

![image](https://user-images.githubusercontent.com/8399207/65138875-97ea9100-da03-11e9-9b54-24ae27baee6a.png)

Note that "JS Plugin Hide" is unchecked, meaning it won't run

**Comment by opusforlife2** [comment]
That's what I thought too. But that's not how it works.

Whitelist normally means it gets an exception from the rule, so that's how I initially set it up. But I noticed it wasn't working as expected. After some testing with Startpage's Anonymous Mode and the Firefox Web Console, I found out that the check boxes under "Applied to all pages" have no effect at all. The check boxes under "Apply only to this entry" do work as expected, though.

This is how I ultimately had to go about it to make it work:

1. Whatever entries are blocking Anonymous Mode from working, are to be put under "Run only on some pages".
2. I use the wildcard to add Startpage's Anonymous Mode to the whitelist.
3. I uncheck all check boxes under "Apply only to this entry". Now Startpage Anonymous Mode is unbroken.

But as a consequence of "Run on some pages" those protections are now useless.

4. So I add a bunch of the most common TLDs to the whitelist, and check all the check boxes for all of them. Now they get the remaining protections activated.

I still cannot do anything about the .com TLD because adding it to the whitelist will override Startpage's entry. The maximum I can do is use the wildcard to protect HTTP-only URLs, as Startpage is HTTPS.

**Comment by opusforlife2** [comment]
@jake-cryptic Did you get the opportunity to test this?

**Comment by jake-cryptic** [comment]
Hi,

Unfortunately I've been very busy these past few weeks so haven't had a chance to do much work on Trace... I will look into this as soon as I have the opportunity to do so.

Thanks for your patience

**Comment by opusforlife2** [comment]
@jake-cryptic I just want to reiterate, now that the UI in version 3 has changed what the settings mean, that in addition to "Runs by default" and "Runs when enabled", there should be an option called "Doesn't run when disabled" so that specific sites can be whitelisted.
