### ISSUE TITLE
Trace add-on causes error in Google Docs

### ISSUE THREAD

**Issue by DanStevens** [jake-cryptic/AbsoluteDoubleTrace#26]
Add-on causes Google Docs (docs.google.com) to stop working - I get the following error whenever I try to open a Google Doc:

> This error has been reported to Google and we'll look into it as soon as possible. Please reload this page to continue.

Disable the add-on resolves the issue. Enabling it again and the error returns. I am using Firefox 68.0.1

1. Open Firefox
2. Install add 'Trace - Online Tracking Protection' via Add-On Manager
3. Open URL https://docs.google.com and open new blank document
4. Observe the error message above.
5. Close the browser tab.
6. Disable the add-on.
7. Repeat step 3 and observe a blank Google Doc is shown

[Screenshot](https://drive.google.com/file/d/1d5piaeYzJGT7oRHrAdUgGVYguc1CHNmJ/view?usp=sharing)

 - OS: Windows 10
 - Browser: Firefox
 - Version: 68.0.1

**Comment by jake-cryptic** [comment]
Hi,

I've just pushed Trace 2.3.6 which should hopefully fix this. Please try it and get back to me.

Thanks
