### ISSUE TITLE
Enabling Screen Resolution Protection Drastically Lowers A Users Anonimity

### ISSUE THREAD

**Issue by Eriksh** [jake-cryptic/AbsoluteDoubleTrace#35]
Color depth on screen resolution protection should be set to a static 24 bits like most other PC and phone OS's.  Due it it being currently configured as random, the user stands out and easily traced.

![Resolution Issue](https://user-images.githubusercontent.com/3190487/66710566-ce010380-ed6a-11e9-95e4-a058d56704f4.PNG)

**Comment by jake-cryptic** [comment]
I'll add an option to disable this setting in an update soon.

Thanks for raising this

**Comment by jake-cryptic** [comment]
This fix has been added to Trace and will be available in the next update.
