### ISSUE TITLE
Enabling common tracking protection breaks site

### ISSUE THREAD

**Issue by monterrr** [jake-cryptic/AbsoluteDoubleTrace#36]
**Describe the bug**
Enabling common tracking protection breaks `https://bethesda.net/en/dashboard` even with all settings disabled on the configuration of common tracking protection.

**To Reproduce**
1. Enabling common tracking
2. Disable all configuration settings on Enabling common tracking

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 2.4.1

**Comment by jake-cryptic** [comment]
I am aware of the issues and feel that they may take some time to fix... Common tracking protection will be disabled in 2.4.2 as a result until it's fixed

**Comment by jake-cryptic** [comment]
Closing this issue as a duplicate, further discussions to be held at #32
