### ISSUE TITLE
Submit a ticket at support.gearbest.com doesn't work with trace enabled

### ISSUE THREAD

**Issue by monterrr** [jake-cryptic/AbsoluteDoubleTrace#38]
**Describe the bug**
Submitting a ticket at support.gearbest.com doesn't work with trace enabled, it doesn't do anything the submit button.

**To Reproduce**
1. Go to support.gearbest.com
2. Try to create a ticket
3. Doesn't do anything

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 70

**Comment by jake-cryptic** [comment]
Hi,

If you're still having this issue on Trace v3 please reopen this issue. Lots of code has changed since v2.4 and so the issue may now be resolved. If not, please send over a Trace backup file which can be created from Trace's options page and reopen the issue.

Thanks
