### ISSUE TITLE
With webrtc protection on firefox won't open photos windows

### ISSUE THREAD

**Issue by monterrr** [jake-cryptic/AbsoluteDoubleTrace#39]
**Describe the bug**
With Webrtc protection on, Firefox won't open a new window of images at: https://app.planetexpress.com

**To Reproduce**
1. Must have a package on account and create an account.
2. Click on the photos
3. Won't open a new window

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 70

**Comment by jake-cryptic** [comment]
Hi,

If you're still having this issue on Trace v3 please reopen this issue. Lots of code has changed since v2.4 and so the issue may now be resolved. If not, please send over a Trace backup file which can be created from Trace's options page and reopen the issue.

Thanks
