### ISSUE TITLE
Security threat to VPN user(s)!

### ISSUE THREAD

**Issue by manrayer** [jake-cryptic/AbsoluteDoubleTrace#40]
Using Firefox Quantum (v70) on Windows 10, 64bit. My VPN circuit starts on my ASUS router to the VPN provider. It does not involve Windows software in any way.

Normally when using the VPN, the client **and** the exit node **and** the DNS share the same IP address - so there's no possibility of DNS leakage. However, when Trace is enabled, two 'rogue' DNS severs appear simultaneously (with the same IP address!)  between my client and the VPN providers DNS server - one time they were located in Texas and another time in Japan, etc. This is according to ipleak.net and has caused consternation at my VPN provider.

Perhaps this is Cloudflare? Is this a security concern? If this is necessary to the function of Trace (but compromises VPN security), then a very clear warning should be made on the Mozilla addon page and in the privacy policy. Even if there is NOT a security issue, users should be apprised of the potential/probably Trace interaction with a VPN circuit.

**Comment by jake-cryptic** [comment]
Trace does not interact with VPNs at all in your browser, it is not possible for Trace to even do so with the current permission set...

The only setting that could be messing with ipleak.net is the Proxy IP Header Spoofing, please try disable that and see if the issue persists. Otherwise I cannot see this being an issue with Trace...

**Comment by geeknik** [comment]
Could be that DNS over HTTPS has been enabled in your Firefox profile. To verify:

1) Click the menu button, click **Preferences**.
2) In the **General** panel, scroll down to **Network Settings** and click the **Settings** button.
3) In the dialog box that opens, scroll down to **Enable DNS over HTTPS**.
    * **On**: Select the _Enable DNS over HTTPS_ checkbox. Select a provider or set up a custom provider. 
    * **Off**: Deselect the _Enable DNS over HTTPS_ checkbox. 
4) Click **OK** to save your changes and close the window.
