### ISSUE TITLE
Clarify extension's compatibility with Firefox on android 

### ISSUE THREAD

**Issue by monterrr** [jake-cryptic/AbsoluteDoubleTrace#41]
There should be a clarification if this extension works on Firefox for android, it is possible to install the addon but the addon's page warns that "This listing is not intended for this platform".

Once installed the interface seems to work good though.

**Comment by jake-cryptic** [comment]
I'll take a look at changing this in the next update to Trace and will update this issue once it is out.

**Comment by jake-cryptic** [comment]
I tested on my phone and the message has been removed as of v3.0
