### ISSUE TITLE
ghacks privacy user.js template

### ISSUE THREAD

**Issue by ToEatFreshBabies** [jake-cryptic/AbsoluteDoubleTrace#43]
Are you aware of the ghacks project?

https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview

**Comment by jake-cryptic** [comment]
I've heard of the project but haven't looked into it.

Is there anything specific you would like to point out about it? I have noticed it has a list of test sites in the wiki that may be useful for me to test Trace with.
