### ISSUE TITLE
Missing links to 'Trace Source' and 'Submit Issue'

### ISSUE THREAD

**Issue by rolandog** [jake-cryptic/AbsoluteDoubleTrace#46]
**Describe the bug**
I think more people could contribute with feedback if links to the repository and issue-tracker were included in the Info section.

**To Reproduce**
1. Go to 'tr' (trace's add-on button)
2. Click on 'Settings'
3. Click on 'Info'
4. Scroll towards the bottom of the page

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Firefox
 - Version 75.0b2 (64-bit)

**Additional context**
None.

**Comment by jake-cryptic** [comment]
I hadn't realised that there wasn't a link to the source code in the "Info" section. This will be added in the next update.

Thanks
