### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by atomGit** [jake-cryptic/AbsoluteDoubleTrace#5]
this looks like a very promising extension - has the [ghacks](https://github.com/ghacksuserjs/ghacks-user.js) crew been in touch?

i have some questions - if you like i will open new issues for any of these which you wish to address...

1. [CSS Exfil](https://www.mike-gualtieri.com/css-exfil-vulnerability-tester) - any plans to address this?
2. i saw in your change-log/to-do list that you plan on expanding the UA stuff - when RFP is enabled (firefox), this messes with the UA that AMO detects - it would be nice if the real UA could be sent to such sites without disabling RFP
3. [rel=noopener](https://addons.mozilla.org/en-US/firefox/addon/dont-touch-my-tabs/) - any chance of incorporating this?
4. what about the X-Forwarded-For header?
5. [poop](https://github.com/claustromaniac/poop) might interest you?
6. window.opener - it looks like you may be addressing this in the future?

**Comment by jake-cryptic** [comment]
Ghacks haven't been in touch, but I am aware of the article they wrote https://www.ghacks.net/2018/05/12/trace-blocks-multiple-tracking-techniques-in-firefox-and-chrome/ and I found it helpful looking through the comments seeing what features/changes were wanted.

To answer your questions:

1. I have looked into tackling this issue a few times, however, it seems as though it would be rather hard to mitigate/prevent... I will take a look into it though as I just saw the demonstration of it and it seems a lot worse than I remember it being a few months ago.

2. I'll look in to RFP messing up this protection and see what I can do

3. If my current understanding is correct, this feature would be very easy to implement and I could probably have a beta version of it ready for 2.1

4. Trace can spoof X-Forwarded-For headers using the Proxy IP Header Spoofing option in settings - however I am aware of a few bugs that this currently has which need fixing - overall it works though.

5. "poop" looks very interesting, I'm unsure if I'd be able to access those headers on Chrome but I will look into it and update this issue thread accordingly.

6. I was planning on addressing this in the 2.0 update, I have it written down on some planning documents somewhere... I shall update this thread soon as to when you can expect an implementation.

If there's anything else, feel free to let me know, or if you want me to expand on anything I said I'll try my best to do so :)

**Comment by atomGit** [comment]
re: ghacks - they have a fairly well known [repo on GitHub](https://github.com/ghacksuserjs/ghacks-user.js) where they create a custom user.js - it's a highly dynamic project with some very knowledgeable peeps (one from Moz apparently) - their wiki is pretty good to

re: CSS exfil - if you want to address that you could look at the code for [CSS Exfil Protection](https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/)

regarding UA revealing (or spoofing) for sites like AMO, i dunno if the new API can mess with browser prefs anymore, but if this helps...
`general.useragent.site_specific_overrides`
`general.useragent.override.addons.mozilla.com` (has to be created)

regarding link cleaning, if you want to expand your list, this might be of value (or not)...

https://gitlab.com/KevinRoebert/ClearUrls
https://gitlab.com/KevinRoebert/ClearUrls/raw/master/data/data.json
https://addons.mozilla.org/en-US/firefox/addon/neat-url/

**Comment by jake-cryptic** [comment]
I'll take a look into the Ghacks repo :)

Regarding the CSS Exfil, I was taking a look at some web tracking using CSS and it seems as though it will be very hard to block completely without significant detriment to the user experience on the web... So I've been working on a mitigation today, I'll share it soon and a beta test will be available.

As for the other two items you mention, I shall certainly take a look. I do wish to expand the list of URL parameters and in future allow users to add their own :)

**Comment by atomGit** [comment]
... let me expand on that ghacks idea a bit more

a lot of the settings in their user.js can be set and forgotten because they will almost never break things, however some will break website functionality and this can be a significant problem for those that want the privacy/security benefits of their config because troubleshooting which pref busted what can be very time consuming

what i'm trying to pawn off on you (or anyone) is to create a GUI front end for their prefs (and your own) only for those that can fairly commonly brake stuff - from the UI one can toggle the prefs as they like, but there would also be a whitelist so that when some pref breaks something on a site, one can set that pref to a default/different value automatically when they visit that site rather than having to switch profiles or whatever

**Comment by atomGit** [comment]
got a question which i can create a new issue from if necessary - from the toolbar icon, what's the 'home' link for? it doesn't do anything

and for the whitelist, when i click 'apply this', i expect to find the entry in the settings -> whitelist panel, but it's always empty

**Comment by jake-cryptic** [comment]
The thing is Trace wouldn't be able to change the settings like the ghacks can as extensions are very limited in what they can do. For example, I can't fully implement the E-Tag tracking protection because the web request api doesn't allow me to edit all the headers I need to :(

I think that if somebody were to create a UI for the GHacks script they'd need it to be a desktop application as that would be the only thing that could modify the browser settings.

I'm planning on updating the whitelist panel and 'blocked page' as they both can be confusing and buggy... The home button just takes you back to the default screen in it..

**Comment by jake-cryptic** [comment]
I've enabled projects for this repo and have added some of your suggestions to them

**Comment by atomGit** [comment]
i take it the WebExt API does not allow changing internal browser prefs than? if so that was a terrible oversight on my part - sorry

i'll let you close this if you want, and thanks for your comments

**Comment by jake-cryptic** [comment]
Unfortunately no it doesn't - extensions really can't do as much as most people think :/

Thank you for the suggestions though!
