### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by comradekingu** [jake-cryptic/AbsoluteDoubleTrace#50]
Not having a license makes the project proprietary.
It would be much preferable to pick a libre software license before accepting
PRs. :)

Edit: Just noticed "This repo will not accept contributions."

**Comment by jake-cryptic** [comment]
I am aware of licensing for open source software, as you mention in your edit the repo does not accept contributions.

Should this position change, a license will be added to the repo, most likely the GNU General Public License v3.0.
