### ISSUE TITLE
collaborate with tor-browser ?

### ISSUE THREAD

**Issue by 1000i100** [jake-cryptic/AbsoluteDoubleTrace#55]
Tor-browser work on radical privacy, you to, and a part of it look to be the same in my eyes.

Do you speak with them ? Do you collaborate on some stuff ?

**Comment by jake-cryptic** [comment]
Hi,

I've never been in contact with anybody at Tor.

**Comment by 1000i100** [comment]
And are you interested to become in contact ?

**Comment by jake-cryptic** [comment]
Not at the moment because I am very busy with other work
