### ISSUE TITLE
Feature list modification

### ISSUE THREAD

**Issue by aelisya** [jake-cryptic/AbsoluteDoubleTrace#62]
For web request list, can you let us add our own copy of the non-premium list ? (so like that, we can replicate the free list on another server and reduce the load of your).

Two advantages,
1. For us who own server we can use trace without connection to your server (better for privacy (if not premium of course)).
2. For you, you have mirror of the free list (surly the most used one) your server load will be reduced.

If you don't want to let personal list in the extension (for those who will integrate their own list), can you at least host the free list on github (like that people can read the free list if they want))

**Comment by jake-cryptic** [comment]
Hi,

I will reply with more details soon but just quickly, the extension already comes with a local copy of the regular list and there is a copy on my github which is used as a fallback.

Links:
https://github.com/jake-cryptic/hmfp_lists
https://github.com/jake-cryptic/AbsoluteDoubleTrace/blob/master/MyTrace/data/blocklist.json

Thanks

**Comment by aelisya** [comment]
i see thanks
