### ISSUE TITLE
Whitelist: this is a bug or feature?

### ISSUE THREAD

**Issue by madhook** [jake-cryptic/AbsoluteDoubleTrace#7]
If I disable 'Web Request Controller', after restart Firefox my Whitelist is going to blank (empty).
If I enable 'Web Request Controller' and restart Firefox, then Whitelist is back as was.
?

**Comment by Atavic** [comment]
A feature, see: https://github.com/jake-cryptic/AbsoluteDoubleTrace/blob/46859325aab2b763af2eb6bdb319d3acfc326d5b/MyTrace/js/pages/options.js#L470

*Whitelist* is handled by Web Request Settings.

**Comment by Atavic** [comment]
A feature, see:

https://github.com/jake-cryptic/AbsoluteDoubleTrace/blob/46859325aab2b763af2eb6bdb319d3acfc326d5b/MyTrace/js/pages/options.js#L469

Whitelist is handled by Web Request Settings.

**Comment by jake-cryptic** [comment]
I see the issue - I will take a look into this now

**Comment by jake-cryptic** [comment]
Trace 2.1.3 pushed with fix included
