### ISSUE TITLE
Trace with defaults breaks Selenium 4 mouse actions

### ISSUE THREAD

**Issue by Obie-Wan** [jake-cryptic/AbsoluteDoubleTrace#73]
Add trace to browser.
Run selenium test with mouse automation on any element:
ActionChains(driver).move_to_element(element).perform()
Willl have an exception:
```
selenium.common.exceptions.JavascriptException: Message: javascript error: rects is not iterable

```

**Comment by underrobyn** [comment]
Trace is not intended to be used with Selenium
