### ISSUE TITLE
WebGL Generating random noise each value

### ISSUE THREAD

**Issue by Renan19** [jake-cryptic/AbsoluteDoubleTrace#9]
This bronke some websites and destroy any try to use it in serious financial websites or commerce websites.
a normal use dont change fingerprin each page load, the system can see this changes.

Please, put a option to lock fingerprints and only load a new when we realease a previous fingerprint.
In WebGL, a option to choose what device we want to spoof will be very god. a single button to "generate new noise" sounds good, and option to DONT change noise each load.

and another problem is in https://browserleaks.com/webgl we can see only the frist hash, second hash never generated.

thanks for great work.

**Comment by jake-cryptic** [comment]
Hi,

The WebGL fingerprinting protection is very new and I will be adding new features to it in the next update. However at the moment I'm very busy with exams and so I can't give an ETA of when this update will be coming.

I'll update the Trace 2.3 project with your suggestions though so I don't forget :)

Thanks!

**Comment by Renan19** [comment]
I will wait anxiously.
Thanks for the answer and I wish all the luck in your exams, I know how difficult it is.
Thank you.

**Comment by jake-cryptic** [comment]
Added option to configure WebGL Fingerprinting in Trace 2.4
